### ISSUE TITLE
Sample query doesn't work, return empty result

### ISSUE THREAD

**Issue by Yunlong-He** [ramnes/notion-sdk-py#187] opened 2023-04-19 03:58 UTC
With guide in first project, I duplicated the page in my workspace, and I also created one integration, but don't know how to add the integration to that page,

In README:
Lastly we need a notion page to experiment with. Duplicate [this page](https://www.notion.so/notion-sdk-py-540f8e2b79914654ba103c5d8a03e10e) in your workspace. Click on Share, and add your integration to this page.

I clicked Share, there are only permission settings, to everyone in this workspace, but can't find integrations there

**Comment by Yunlong-He** [comment] 2023-04-19 04:08
The error shows:
====================================
Searching for the word 'People'
0
Traceback (most recent call last):
  File "/home/ubuntu/lab/test/notionai/test.py", line 16, in <module>
    result = results[0]
             ~~~~~~~^^^
IndexError: list index out of range

**Comment by ramnes** [comment] 2023-04-19 08:10
Yes, it looks like the way to add an integration to a page changed.

From https://developers.notion.com/docs/authorization#integration-permissions:

> To share a page with an integration, visit the page in your Notion workspace, click the ••• menu at the top right of a page, scroll down to Add connections, and use the search bar to find and select the integration from the dropdown list.

Does that help?

If so, feel free to open a PR and correct the example README!

(Note to myself ­– The issue is about [this README](https://github.com/ramnes/notion-sdk-py/tree/main/examples/first_project), not the main README.)

**Comment by Yunlong-He** [comment] 2023-04-19 08:48
@ramnes Thanks very much, the new way works well and the script runs ok.

I will open a PR today.

**Comment by ramnes** [comment] 2023-04-19 09:36
Closed in c559bebe11507406bddcac3fbae6304801d95a6d.

Thanks again!

**Closed by ramnes** 2023-04-19 09:36 UTC
Labels: documentation, help wanted, good first issue, task
