### ISSUE TITLE
Defining Data Transfer Objects (in terms of `@dataclass`) for easier development

### ISSUE THREAD

**Issue by jkgrad** [ramnes/notion-sdk-py#133] opened 2022-06-08 05:32 UTC
Hello, thank you for creating such a great project.

I was wondering if there is a plan to add pre-defiend DTOs for API request / response since the official API is out of beta.

Currently, API endpoint invocations return generic `SyncAsync[T]` types, which makes development a bit cumbersome.

From what I am aware of, the following libs are options for defining DTOs:
- `dataclasses` is built-in from 3.7, but cannot serialize / deserialize nested object (`dataclasses-json`).
-  `pydantic` has good serialization / deserialization features, but a bit heavier than the other.

**Comment by ramnes** [comment] 2022-06-08 09:59
Hi, and thanks for the kind words!

This is a duplicate of #9, have a look if you want more context.

I guess you'll be interested in @jheddings' abstraction, [notional](https://github.com/jheddings/notional).

**Closed by ramnes** 2022-06-08 09:59 UTC
