### ISSUE TITLE
🐛 Boolean always evaluated to `True`

### ISSUE THREAD

**Issue by astariul** [ramnes/notion-sdk-py#38] opened 2021-05-22 14:32 UTC
I'm trying to generate text with styling.

For example, if I want bold + italic text on a blue background, I do the following :

```python
from notion_client import Client

text = {
    "object": "block",
    "type": "paragraph",
    "paragraph": {
        "text": [
            {
                "type": "text",
                "text": {"content": "Test"},
                "annotations": {
                    "bold": True,
                    "italic": True,
                    "strikethrough": False,
                    "underline": False,
                    "code": False,
                    "color": "blue_background",
                },
            }
        ]
    },
}

notion = Client(auth=AUTH_TOKEN)
notion.blocks.children.append(block_id=BLOCK_ID, children=[text])
```

---

Expected result :
![image](https://user-images.githubusercontent.com/43774355/119230058-9452ca00-bb55-11eb-8d9d-279eb3e123bf.png)

Actual result :
![image](https://user-images.githubusercontent.com/43774355/119230085-ac2a4e00-bb55-11eb-98d7-1c6ab258b246.png)

Every boolean annotations are set to `True`, I don't know why...

---

It works properly if simply remove the annotations I want to set to `False` :

```python
text = {
    "object": "block",
    "type": "paragraph",
    "paragraph": {
        "text": [
            {
                "type": "text",
                "text": {"content": "Test"},
                "annotations": {
                    "bold": True,     # Note : I can set this to False, the result is the same
                    "italic": True,     # Note : I can set this to False, the result is the same
                    "color": "blue_background",
                },
            }
        ]
    },
}
```

**Comment by ramnes** [comment] 2021-06-08 08:57
Hi @astariul, sorry for the long time to answer. Did you try calling the API with something else than notion-sdk-py (e.g. cURL) to check if the problem is on our side or Notion's?

**Comment by ramnes** [comment] 2022-11-30 18:01
Closing due to the lack of answer but if you still have the issue (or anyone else), feel free to comment and I'll reopen!

**Closed by ramnes** 2022-11-30 18:01 UTC
